name: Deployment

on: workflow_dispatch

jobs:
  CI:
    uses: ./.github/workflows/CI.yml
  Deploy:
    needs: CI
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        name: Download Artifacts
      - name: Display structure of downloaded files
        run: |
          for i in $(ls); do                                                                                      
          if [ -d $i ]; then                                                                                                         
              fname=${i##*/}                                                                               
              cd $i                                                                                                    
              for z in *; do                                                                                                                    
              zip -r ../${fname}-${z}.zip ./*                                                                                                     
              done
              cd ..
              fi
          done
          ls -R
      - uses: softprops/action-gh-release@v1
        name: Release
        with:
          tag_name: latest
          body: |
            [**Buildlog**](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id}})
          files: '*'
