name: Deployment

on: workflow_dispatch

jobs:
  CI:
    uses: ./.github/workflows/CI.yml
  Deploy:
    needs: CI
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        name: Download Artifacts
      - name: Repack Artifacts
        run: |
          for i in $(ls); do                                                                                      
          if [ -d $i ]; then                                                                                                         
            fname=${i##*/} 
            cd $fname
            for z in *; do
              tar -xvf $z --one-top-level=../tmp/$fname
            done
            cd ..
          fi
          done
          mkdir -p ./Artifacts
          cd ./tmp
          for i in $(ls); do                                                                                      
          if [ -d $i ]; then                                                                                                         
            fname=${i##*/}                                                                               
            cd $i                                                                                                    
            for z in *; do                                                                                                                    
              zip -r ../../Artifacts/${fname}-${z}.zip ./*                                                                                                     
            done
            cd ..
            fi
          done
          cd ..

      - uses: softprops/action-gh-release@v1
        name: Release
        with:
          target_commitish: ${{ github.sha }}
          tag_name: latest
          body: |
            [**Buildlog**](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id}})
          files: 'Artifacts/*'

      - name: Update tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/latest',
              sha: context.sha,
              force: true
            })
