name: Web CI

env:
  EM_VERSION: 3.1.47
  CACHE_FOLDER: '.cache'
  DIST_DIR: 'build/Release.WASM/dist'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Format:
    uses: ./.github/workflows/FormatCheck.yml

  Publish:
    needs: Format
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ${{env.CACHE_FOLDER}}
          key: WASM.cache#${{ github.sha }}
          restore-keys: WASM.cache#
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.CACHE_FOLDER}}/emsdk
      - name: Setup CMake
        uses: lukka/get-cmake@latest
      - name: Build Target
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'Release.WASM'
          buildPreset: 'Release.WASM'
          buildPresetAdditionalArgs: "['--target HelloTriangle']"
      - name: Upload Pages Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{env.DIST_DIR}}
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
